export const purokData = {
  Bulusan: {
    Bagacay: ["Purok 1", "Purok 2", "Purok 3", "Purok 4"],
    Central: ["Purok A", "Purok B", "Purok C", "Purok D"],
    Cogon: ["Purok Uno", "Purok Dos", "Purok Tres"],
    Dancalan: ["Purok Maharlika", "Purok Bayanihan", "Purok Pag-asa"],
    Dapdap: ["Purok 1", "Purok 2", "Purok 5", "Purok 6"],
    Lalud: ["Purok Uno", "Purok Tres", "Purok Sais"],
    Looban: ["Purok A", "Purok B", "Purok C", "Purok D"],
    Mabuhay: ["Purok Silangan", "Purok Kanluran", "Purok Gitna"],
    Madlawon: ["Purok 1", "Purok 3", "Purok 5", "Purok 7"],
    Poctol: ["Purok Uno", "Purok Dos", "Purok Tres", "Purok Kwatro"],
    Porog: ["Purok Alpha", "Purok Beta", "Purok Gamma"],
    Sabang: ["Purok Uno", "Purok Dos", "Purok Tres"],
    Salvacion: ["Purok Kalikasan", "Purok Pag-asa", "Purok Bagong Buhay"],
    "San Antonio": ["Purok 1", "Purok 2", "Purok 3", "Purok 4"],
    "San Bernardo": ["Purok Uno", "Purok Dos", "Purok Tres", "Purok Apat"],
    "San Francisco": ["Purok 1", "Purok 2", "Purok 3"],
    "San Isidro": ["Purok 1", "Purok 2", "Purok 3", "Purok 5"],
    "San Jose": ["Purok 1", "Purok 2", "Purok 3", "Tungod"],
    "San Rafael": ["Purok Uno", "Purok Dos", "Purok Tres"],
    "San Roque": ["Purok Maharlika", "Purok Bayanihan", "Purok Pag-asa"],
    "San Vicente": ["Purok 1", "Purok 2", "Purok 5", "Purok 6"],
    "Santa Barbara": ["Purok Uno", "Purok Tres", "Purok Sais"],
    Sapngan: ["Purok A", "Purok B", "Purok C", "Purok D"],
    Tinampo: ["Purok Silangan", "Purok Kanluran", "Purok Gitna"],
  },

  Irosin: {
    Bacolod: ["Purok Alpha", "Purok Beta", "Purok Gamma"],
    Bagsangan: ["Purok Uno", "Purok Dos", "Purok Tres"],
    Batang: ["Purok A", "Purok B", "Purok C"],
    Bolos: ["Purok 1", "Purok 2", "Purok 3", "Purok 4"],
    Buenavista: ["Purok Maharlika", "Purok Bayanihan"],
    Bulawan: ["Purok Uno", "Purok Dos", "Purok Tres"],
    Carriedo: ["Purok A", "Purok B", "Purok C", "Purok D"],
    Casini: ["Purok 1", "Purok 2", "Purok 5"],
    Cawayan: ["Purok Uno", "Purok Dos"],
    Cogon: ["Purok A", "Purok B"],
    Gabao: ["Purok 1", "Purok 2", "Purok 3"],
    "Gulang-Gulang": ["Purok Uno", "Purok Dos", "Purok Tres"],
    Gumapia: ["Purok 1", "Purok 3", "Purok 5"],
    Liang: ["Purok A", "Purok B", "Purok C"],
    Macawayan: ["Purok Alpha", "Purok Beta", "Purok Gamma"],
    Mapaso: ["Purok Uno", "Purok Dos", "Purok Tres"],
    Monbon: ["Purok 1", "Purok 2", "Purok 3"],
    Patag: ["Purok A", "Purok B"],
    Salvacion: ["Purok Kalikasan", "Purok Pag-asa"],
    "San Agustin": ["Purok 1", "Purok 2"],
    "San Isidro": ["Purok Alpha", "Purok Beta"],
    "San Juan": ["Purok Uno", "Purok Dos"],
    "San Julian": ["Purok 1", "Purok 3", "Purok 5"],
    "San Pedro": ["Purok A", "Purok B"],
    "Santo Domingo": ["Purok Uno", "Purok Dos", "Purok Tres"],
    "Tabon-Tabon": ["Purok 1", "Purok 2"],
    Tinampo: ["Purok A", "Purok B", "Purok C"],
    Tongdol: ["Purok Uno", "Purok Dos", "Purok Tres"],
  },
};
